//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problems
    {
        public int ProblemId { get; set; }
        public string ProbDescription { get; set; }
        public string Photo { get; set; }
        public int MachineId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateProb { get; set; }
        public string Statut { get; set; }
        public bool Fixed { get; set; }
    
        public virtual Machines Machines { get; set; }
    }
}
