//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problems
    {
        public int ProblemId { get; set; }
        public string ProbDescription { get; set; }
        public string Photo { get; set; }
        public int MachineId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateProb { get; set; }
        public string Statut { get; set; }
        public bool Fixed { get; set; }
        public string UserEmail { get; set; }
    
        public virtual Machines Machines { get; set; }
        public virtual Users Users { get; set; }
    }
}
